services:
  caddy:
    image: caddy:latest
    container_name: caddy_public
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
    volumes:
    - ${PWD}/data:/data
    - ${PWD}/config:/config
    - ${PWD}/caddyfile:/etc/caddy
